name: Github release
on:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if should release
        id: should-release
        uses: ./
        with:
          telegram-api-token: ${{ secrets.TELEGRAM_API_TOKEN }}
          telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          question: 'Should release to Github the latest tag?'
          options: '["yes", "no"]'
          default-choice: 'no'
          message: 'The selected choice is: %s'
          timeout: 60
          wait-for-timeout-to-finish: true

      - name: Exit if should not release
        if: steps.should-release.outputs.user-choice == 'no'
        run: exit 0

      - name: Get package version
        run: echo "LATEST_TAG=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          tag: 'v${{ env.LATEST_TAG }}'
          generateReleaseNotes: true
